services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    env_file: ./php/.env
    tty: true
    ports:
      - "8080:80"
    environment:
      - TZ=Asia/Tokyo
